### PR TITLE
Updated readme with more facts and formatting

### PR DESCRIPTION
**Pull request by samdark**
Additional info for readme. Thanks for the project. It works well.

### CODE REVIEW

**Comment by deemru** [comment]
# php.ini loading

image

As you can see on the screenshot above, "php.ini" will be found in an appropriate directory even if you call "php-cgi.exe" from other.

"php.ini" loading logic is out of the scope of this project, but the usage of "-c" parameter should be noticed, thank you.

# thread safe PHP

Why PHP must be a thread safe (ts)? I use a non thread safe (nts) version of PHP for years and did not catch any thread related problems. php-cgi on Windows works synchronously by processing requests one by one. php-cgi-spawner does not bring any change to this processing.

**Comment by samdark** [comment]
How did you run it exactly? [PHP searches ini in current working directory](https://secure.php.net/manual/en/configuration.file.php) since we're running CGI, not CLI. If it's launched from another directory, the directory it's launched from will be current working directory and ini will be searched there.

Forget what I've said about NTS. That was APCu specific issue.

I'll remove this part from pull request.

**Comment by deemru** [comment]
I guess the screenshot above (https://github.com/deemru/php-cgi-spawner/pull/2#issuecomment-165098793) shows the last 3 points form your link (https://github.com/deemru/php-cgi-spawner/pull/2#issuecomment-165102236):

> php.ini is searched for in these locations (in order):

...

> - Current working directory (except CLI).
> - The web server's directory (for SAPI modules), or directory of PHP (otherwise in Windows).
> - Windows directory (C:\windows or C:\winnt) (for Windows), or --with-config-file-path compile time option.

My basic wnp configuration: https://github.com/deemru/secqru-standalone

**Comment by samdark** [comment]
btw., I've tried TS/NTS again. PHP 7. When NTS used it crashes. Could be PHP bug but TS doesn't crash.

**Comment by deemru** [comment]
Seems to depend on an application. How to reproduce?

**Comment by samdark** [comment]
Yes, that's app dependent. I'm not sure what's the reason. Need to install debug symbols to get an idea.

Also it seems cwd and php.ini issue is PHP 7 only.

**Comment by samdark** [comment]
Found the reason. It was using PHP 7 RC1 by mistake. Release version is OK in both cases. Going to adjust readme a bit.

**Pull request merged**
